COIN-1146 make info accept colors and add networkFees infoBox
Ledger-Coin-Integration-team/ledger-live-mobile pull request #7
Opened 2021-01-27 16:25 UTC by henri-ly

Not sure where i can post in but in https://ledgerhq.atlassian.net/browse/COIN-1146 you will find some screens

2021-01-27 16:28 UTC, henri-ly commented on src/components/ValidateOnDevice.js
> +      {mainAccount.currency.family === "polkadot" ? (
I don't like the way of doing this, we don't have anyway without a "refacto" to know if the coin doesn't display the network Fees on the device.
I just made it work on the scope of polkadot. But if you have a more elegant way of doing it, i'm in

2021-02-03 15:49 UTC, haammar-ledger approved these changes

2021-02-05 13:56 UTC, haammar-ledger approved these changes

2021-02-08 17:22 UTC, rjarasson-ledger requested changes

2021-02-08 17:22 UTC, rjarasson-ledger commented on src/locales/en/common.json
> +    "networkFees": "Network fees are automatically set by the Polkadot consensus, you won't be able to review them on your device"
I would have put this at the beginning of the polkadot key (with the lockedBalance etc.. translation).But that's really a minor suggestion. Ignore if there is no other change to do.

2021-02-08 17:22 UTC, rjarasson-ledger commented on src/locales/en/common.json
> +    "memo": "Memo",
I don't think it's ok.
JSON usually does not allow trailing comma.

2021-02-08 17:22 UTC, rjarasson-ledger commented on src/locales/fr/common.json
> +    "memo": "Memo",
no trailing comma.

2021-02-09 13:12 UTC, closed without merging